version: '3.9'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: my_db
      MYSQL_ROOT_PASSWORD: passmysql
    ports:
      - "3306:3306"

