name: Run tests in Docker 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker compose build

    - name: Run app container
      run: docker compose up -d app

    - name: Check container status
      run: docker ps -a

    - name: Show DB logs
      run: docker logs $(docker ps -a -q --filter name=registro_infracciones-db-1)

    - name: Run tests inside container
      run: docker compose run --rm app pytest

    - name: Stop containers
      run: docker compose down

